version: '3'

services:
  postgres:
    image: postgres:10.19-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./:/home/
    ports:
      - 5432:5432
