version: '3'
name: registry
services:
  registry:
    restart: always
    image: registry:2.7.0
    ports:
      - 5001:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.htpasswd
    volumes:
      - ./data:/data
      - './auth:/auth'
